Fire education - release
duckduckgo/Android pull request #1022
Opened 2020-11-25 13:13 UTC by cmonfortep

Task/Issue URL: 
Tech Design URL: 
CC: 

**Description**:

**Steps to test this PR**:
1. 
1. 

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2020-11-25 14:49 UTC, cmonfortep commented on app/src/androidTest/java/com/duckduckgo/app/browser/BrowserTabViewModelTest.kt
> +    fun whenFirePulsingAnimationStartsThenItStopsAfterOneHour() = coroutineRule.runBlocking {
This test was missing and it was requested on a previous review.

2020-11-25 14:50 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/global/db/AppDatabase.kt
> +            database.execSQL("UPDATE $USER_STAGE_TABLE_NAME SET appStage = \"${AppStage.ESTABLISHED}\" WHERE appStage = \"${AppStage.DAX_ONBOARDING}\"")
As per https://app.asana.com/0/0/1199221440116910/f

2020-11-26 12:08 UTC, marcosholgado requested changes
Nice job! Looks pretty good, just a few minor comments plus what we talked about on zoom regarding that flow :)

2020-11-27 00:58 UTC, cmonfortep commented on app/src/androidTest/java/com/duckduckgo/app/cta/ui/CtaViewModelTest.kt
> +        givenControlGroup()
👍

2020-11-27 01:04 UTC, cmonfortep commented
@marcosholgado this is now ready for a second review. Database updates should now be fixed. And there's a small improvement to stop receiving updates from databases when fire pulsing animation is not going to be active again.

2020-11-27 10:41 UTC, marcosholgado approved these changes
Nice job @cmonfortep! I left a minor comment in a couple of places regarding the println statement, nothing major so feel free to merge!

2020-11-27 10:41 UTC, marcosholgado commented on app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
> +                    println("pulseAnimationDisabled")
Nit: do we need this print?

2020-11-27 10:41 UTC, marcosholgado commented on app/src/main/java/com/duckduckgo/app/cta/ui/CtaViewModel.kt
> +                println("collectedcta $dismissedCtaDao")
Nit: do we need this print?

2020-11-30 13:06 UTC, merged