User Credential on Android system being presented when accessing Mutu…
duckduckgo/Android pull request #1078
Opened 2021-01-27 21:22 UTC by theyoz

Task/Issue URL:  https://github.com/duckduckgo/Android/issues/1063

**Description**:

Hi,

This code does the trick for our sites. It is important to note that RSA keys ONLY are requested by this pull request, I didn't test it with EC keys et al (see [choosePrivateKeyAlias](https://developer.android.com/reference/android/security/KeyChain#choosePrivateKeyAlias(android.app.Activity,%20android.security.KeyChainAliasCallback,%20java.lang.String[],%20java.security.Principal[],%20java.lang.String,%20int,%20java.lang.String)) field keyTypes

However RSA is the most common and if adding the rest to the String[] list still works, you may as well.

My apologies for proposing a change, I really want to you DuckDuckGo but without this I can't :)

This fix does not fix the certificate download but that is the easier part.

###### Internal references:
[From Issue](https://app.asana.com/0/414730916066338/1199561121099458/f)

2021-01-29 11:19 UTC, aitorvs commented
Thanks for this PR! we'll be working internally in a generic solution that works for all sites. I think it's best to close this one for now and wait for the more generic one.

2021-02-01 08:46 UTC, initpwn requested changes
Not generic.

2021-02-15 06:28 UTC, theyoz commented
Hi,

Just to let you know that the server on which I installed the test site will run out on 5 mars 2021. Let me know if you need any more help from me.
Thanks

2021-02-18 10:29 UTC, cmonfortep commented
Thanks @theyoz, and sorry for the unclarity here. We've decide to work on this internally, so I will close this PR. Thanks for the setup and your time here, but we are going to provide a generic solution that works for all sites.

2021-02-18 10:29 UTC, closed without merging