Feature/cristian/webview darktheme
duckduckgo/Android pull request #1314
Opened 2021-07-12 14:32 UTC by cmonfortep

Task/Issue URL: https://app.asana.com/0/414730916066338/1174433894299360/f
Tech Design URL: 
CC: 

**Description**:

**Steps to test this PR**:
1. 
1. 

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2021-09-13 09:53 UTC, malmstein approved these changes
works as expected, nice add @cmonfortep !

2021-09-15 09:59 UTC, malmstein requested changes
@cmonfortep after the changes introduced by https://github.com/duckduckgo/Android/pull/1398 this no longer works as expected. 

- Select system theme in Settings
- Select dark them in device settings
- WebView should be dark, but it's light (Twitter.com)

2021-09-15 10:07 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
> +        val currentNightMode = resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
should be fixed now @malmstein

2021-09-15 10:11 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
> +        val currentNightMode = resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
Actually, not yet. I will ping you once this is ready to review.

This is failing if you selected light theme but your device is in Dark mode.

2021-09-15 10:32 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
>      private fun configureDarkThemeSupport(webSettings: WebSettings) {
This is now ready for review @malmstein

2021-09-15 12:45 UTC, malmstein approved these changes
This is great, thanks @cmonfortep !

2021-09-15 12:49 UTC, cmonfortep commented
![](https://media2.giphy.com/media/B8MhRFZsRVRmg/giphy.gif?cid=ecf05e47kis58ircasjxo8449t2n44v7kkoy4yxxi4ru3kqe&rid=giphy.gif&ct=g)

2021-09-15 12:49 UTC, merged