System default theme added Fixes #1397
duckduckgo/Android pull request #1398
Opened 2021-08-30 08:30 UTC by 4shutosh

Task/Issue URL: #1397

**Description**:
Added system default theme option for supporting devices Android 10 onwards

**Steps to test this PR**:
1. Open Settings
2. Open theme group
3. Devices above 10 and above will have an option to set the System Default theme option.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2021-08-30 08:30 UTC, 4shutosh commented
Doubts: 
- How do I add all the string values of other language translations, is there any efficient option other than adding them manually?
- Will need the Pixel param for the new SYSTEM_DEFAULT click statistics `AppPixelName:SETTINGS_THEME_TOGGLED_SYSTEM_DEFAULT`

2021-08-30 10:12 UTC, 4shutosh commented
I've added translations as well.

Here is a screenshot of the entire implementation:
![sampleSS](https://user-images.githubusercontent.com/53831987/131323961-c4d74705-8e7b-4d21-b6b8-c12edecae736.jpeg)

Let me know with any changes, Please Review :)

2021-08-30 10:23 UTC, 4shutosh commented
Video Sample for the same:
![videoSample](https://user-images.githubusercontent.com/53831987/131325237-0575e953-e4c4-47a1-b4d6-1e4dccb44cb9.gif)

2021-08-31 15:25 UTC, malmstein commented
@4shutosh thanks for the contribution! We are discussing internally how we want to present the Light / Dark / System options, but it's looking good so far. 

I'll get back to you with the next steps regarding translations, etc...

Good work!

2021-08-31 15:37 UTC, 4shutosh commented
Sure @malmstein, please let me know of any changes required.

2021-09-03 09:51 UTC, malmstein requested changes
Thanks for this @4shutosh!

I've left a few comments, but mostly:

- Delete all the new added translations to different languages. We have an internal process to deal with them
- Move the new added English strings to `strings-untranslated.xml`
- Change order of dialog so System Default is the first item on the list.

2021-09-03 09:51 UTC, malmstein commented on app/src/main/java/com/duckduckgo/app/pixels/AppPixelName.kt
> +    SETTINGS_THEME_TOGGLED_SYSTEM_DEFAULT("ms_tsd"), // confirm? the code here for statistics
this is good, just remove the comment

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/layout/content_settings_general.xml
> +        android:id="@+id/themeToggle"
can you rename this to `selectedThemeSetting` to follow convention? It's not really a toggle anymore.

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
> +    <string name="settingsTheme">Theme</string>
new translations go into `settings-untranslated.xml` and only in English

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
> +    <string name="settingsDarkTheme">Dark Theme</string>
ditto, also let's just have `Dark` and remove `Theme`

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
> +    <string name="settingsSystemTheme">System Default</string>
ditto

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
> +    <!--    Theme Settings-->
ditto

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
> +    <string name="settingsThemeDialogSave">Set Theme</string>
ditto

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/layout/settings_theme_selector_fragment.xml
> +            android:id="@+id/themeSelectorSystemDefault"
can you move System Default to be the first item in the dialog?

2021-09-03 09:51 UTC, malmstein commented on common-ui/src/main/java/com/duckduckgo/mobile/android/ui/Theming.kt
> +    SYSTEM_DEFAULT;
`SYSTEM_DEFAULT` should be the first in the list

2021-09-03 09:51 UTC, malmstein commented on app/src/main/res/values/strings.xml
>      <string name="settingsLightTheme">Light Theme</string>
Can you rename this to only `Light`?

2021-09-03 09:51 UTC, malmstein commented on app/src/main/java/com/duckduckgo/app/settings/SettingsThemeSelectorFragment.kt
> +            arguments?.getSerializable(DEFAULT_OPTION_EXTRA) as DuckDuckGoTheme? ?: SYSTEM_DEFAULT
the default here should be `LIGHT`

2021-09-03 09:55 UTC, 4shutosh commented
On it

2021-09-03 11:17 UTC, 4shutosh commented
- I've removed translations, also moved `settingsLightTheme` string into the untranslated as the string value was changed to "Theme"
- Made System Default on the top of the list

2021-09-03 17:21 UTC, malmstein commented on app/src/main/res/values/string-untranslated.xml
> +    <string name="settingsDarkTheme">Dark </string>
trailing spance

2021-09-03 17:24 UTC, malmstein commented
@4shutosh I left a comment about a space added that's not needed. Also, seems like there are some compilation errors:

```
> Task :app:compilePlayDebugAndroidTestKotlin FAILED
e: /Users/runner/work/Android/Android/app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt: (148, 20): Unresolved reference: onLightThemeToggled
e: /Users/runner/work/Android/Android/app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt: (159, 16): Unresolved reference: onLightThemeToggled
e: /Users/runner/work/Android/Android/app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt: (167, 20): Unresolved reference: onLightThemeToggled
e: /Users/runner/work/Android/Android/app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt: (179, 16): Unresolved reference: onLightThemeToggled
e: /Users/runner/work/Android/Android/app/src/androidTest/java/com/duckduckgo/app/settings/SettingsViewModelTest.kt: (187, 20): Unresolved reference: onLightThemeToggled
```

Once those are fixed we are ready to approve. Let me know if you need any help!

2021-09-06 04:04 UTC, 4shutosh commented
@malmstein I've modified the tests. Please check

I've noticed one thing while implementing this that the `DialogFragments` do not follow the dark theme for some reason. I would like to open an issue for this and work on the same.

2021-09-06 04:25 UTC, 4shutosh commented
Another doubt: There is a `darkThemeSwitch` inside AppComponentsActivity inside the Internal Features, does that require any modification as well?

2021-09-09 18:40 UTC, 4shutosh commented
Is there anything else required to be done from my side @malmstein? Please let me know

2021-09-13 10:13 UTC, malmstein approved these changes

2021-09-13 10:13 UTC, malmstein commented
It's all good now @4shutosh. Thanks for putting in the work!

2021-09-13 10:13 UTC, merged

2021-09-13 10:15 UTC, 4shutosh commented
It's my pleasure. Thank you for you help 🙌🏻