Get data from device for email settings page
duckduckgo/Android pull request #1774
Opened 2022-02-27 21:51 UTC by alistairjcbrown

Task/Issue URL: https://app.asana.com/0/0/1201769496879112/f

### Description
Update to allow requesting user data from Android devices

⚠️  This needs to also include updating autofill, once https://github.com/duckduckgo/duckduckgo-autofill/pull/52 is merged

### Steps to test this PR
1. Build browser
2. Go to my dev instance
3. If needed, log in with production duck email username
4. See "Autofill" tab with duck email and private address generator

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2022-02-28 08:10 UTC, aitorvs requested changes
I left some comments. Most important is about creating unnecessary public properties without using dependency injection and unnecessary data models like `UserData`

Also, can we remove the last commit that modifies the version of autofill? Bumping autofill should be in its own PR.

2022-02-28 08:10 UTC, aitorvs commented on app/src/main/java/com/duckduckgo/app/email/EmailManager.kt
> +
There is not need to create private mutable properties here that also don't go through our dependency injection.
This model is rather simple so I'd rather use `JSONObject`
Also the signature doesn't need to be nullable.

```suggestion
    override fun getUserData(): String {
        return JSONObject().apply { 
            put("token", emailDataStore.emailToken)
            put("userName", emailDataStore.emailUsername)
            put("nextAlias", emailDataStore.nextAlias?.replace(DUCK_EMAIL_DOMAIN, ""))
        }.toString()
    }

```

2022-02-28 08:10 UTC, aitorvs commented on app/src/main/java/com/duckduckgo/app/email/EmailManager.kt
> +    fun getUserData(): String?
nit: Signature doesn't need to be nullable
```suggestion
    fun getUserData(): String
```

2022-02-28 08:10 UTC, aitorvs commented on app/src/main/java/com/duckduckgo/app/email/EmailJavascriptInterface.kt
> +    fun getUserData(): String? {
Signature doesn't need to be nullable
```suggestion
    fun getUserData(): String {
```

2022-02-28 10:18 UTC, alistairjcbrown commented
Thanks so much for reviewing @aitorvs 🙇
I've updated for your comments, and dropped the last commit -- how does this look now?

2022-02-28 11:21 UTC, aitorvs reviewed
This LGTM code wise. Haven't tested it end to end. @marcosholgado can you help with that?

2022-02-28 11:21 UTC, aitorvs approved these changes

2022-02-28 12:10 UTC, marcosholgado commented
Adding a do not merge label, I will add unit tests before merging.

2022-02-28 13:12 UTC, malmstein commented
https://github.com/duckduckgo/Android/actions/runs/1909666883 has been running for 3 hours

2022-03-01 13:46 UTC, marcosholgado approved these changes
Already approved but LGTM. I added unit tests for the new code and a minor change to add the json constants to the companion object. Thanks @alistairjcbrown!

2022-03-01 14:28 UTC, merged