ADS: Make TextAlertDialog Cancellable
duckduckgo/Android pull request #2816
Opened 2023-02-06 15:27 UTC by malmstein

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2023-02-06 15:27 UTC, malmstein commented
Current dependencies on/for this PR:
* develop
  * **PR #2816** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/2816" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/2816?utm_source=stack-comment).

2023-02-07 09:52 UTC, CDRussell requested changes
These changes make it so that **all** `TextAlertDialog` dismiss with the back button, regardless of their `canceable` property.

You can verify this in the internal components->dialog screen, first button ("Text Alert Dialog With Image"): presumably this should **not** dismiss with the back button?

2023-02-07 09:55 UTC, CDRussell commented on app/src/main/java/com/duckduckgo/app/browser/BrowserActivity.kt
> +            .setCancellable(true)
This covers 1 or the 3 cases where you'll need to mark as `cancelable` 

- ✅ `showAppEnjoymentDialog`
- ❌ `showAppRatingDialog`
- ❌ `showGiveFeedbackDialog`

These will also require their corresponding view model functions to be invoked when cancelled, as you've done for `showAppEnjoymentDialog`

2023-02-07 11:09 UTC, CDRussell approved these changes

2023-02-07 12:11 UTC, malmstein commented
Thanks @CDRussell !

2023-02-07 12:11 UTC, merged