Implement sync for Duck Address
duckduckgo/Android pull request #3522
Opened 2023-09-08 09:31 UTC by cmonfortep

Task/Issue URL: https://app.asana.com/0/488551667048375/1205449054184327/f 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2023-09-08 09:31 UTC, cmonfortep commented
Current dependencies on/for this PR:
* develop
  * **PR #3522** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3522" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3522?utm_source=stack-comment).

2023-09-20 12:40 UTC, malmstein requested changes
Test cases work. But, as discussed in the task, I’ve found two issues. Also, we should discuss how you are using hard referenced lambdas to call one class from another instead of using DataObservers like in other syncable features.

2023-09-20 12:40 UTC, malmstein commented on settings/settings-impl/build.gradle
> +    implementation "com.squareup.moshi:moshi-kotlin:_"
```suggestion
    implementation Square.moshi"
```

2023-09-20 12:40 UTC, malmstein commented on settings/settings-impl/src/main/java/com/duckduckgo/settings/impl/SettingsSyncDataPersister.kt
> +            Timber.i("Sync-Settings: process() error parsing credentials ${it.message}")
typo from copy paste?

2023-09-20 12:40 UTC, malmstein commented on settings/settings-impl/src/main/java/com/duckduckgo/settings/impl/SettingsSyncDataPersister.kt
> +        settings: CredentialsSyncEntries,
Copy paste? Should be `SettingsSyncEntries`

2023-09-25 13:50 UTC, malmstein approved these changes
Discussed offline, all good!

2023-09-27 09:55 UTC, cmonfortep commented on app/build.gradle
> +    implementation "com.squareup.moshi:moshi-kotlin:_"
Doesn't seem to be the right dependency. Tried `Square.moshi-kotlin` instead, but doesn't work. I'm not sure what's the short name for this one.

2023-09-27 10:02 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/email/AppEmailManager.kt
> +    init {
Decided to move the discussion in a follow-up task.

Reasons why the current implementation:
- This class is emitting events in `signedInStateFlow` when another part of the code calls `storeCredentials` or `signOut`, but not based on the actual stored values.
- Sync applies changed directly at store level (directly in dao or sharedprefs)
- When that happens we need a way that emailmanager can signal a new event on that flow.
- Current approach, adds a listener to know when sync changes values.

2023-09-27 10:34 UTC, cmonfortep commented on app/src/main/java/com/duckduckgo/app/email/sync/EmailSync.kt
> +    override fun mergeRemote(value: String?): Boolean {
A syncable object should expose 2 different methods for storing data. First will be just to store value without applying any logic. Second will have business logic that decides how to merge local and remote data. The later happens when sync engine strategy is deduplicate.

2023-09-27 10:35 UTC, cmonfortep commented on settings/settings-impl/build.gradle
> +    implementation "com.squareup.moshi:moshi-kotlin:_"
ditto

2023-09-27 10:41 UTC, cmonfortep commented on settings/settings-impl/src/main/java/com/duckduckgo/settings/impl/SyncDateProvider.kt
> +class SyncDateProvider {
While that's true, that belongs to sync implementation details. I'm going to defer this one to discuss how to include it in sync-module so features can rely on sync specific implementation detail.

I think we have similar things in other modules, and we can tackle them at the same time.

2023-09-28 07:24 UTC, merged