Integrate FFS changes on savedsites for sync
duckduckgo/Android pull request #3710
Opened 2023-10-18 08:52 UTC by cmonfortep

Task/Issue URL: https://app.asana.com/0/488551667048375/1205741811092048/f

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2023-10-18 08:53 UTC, cmonfortep commented
Current dependencies on/for this PR:
* develop
  * **PR #3704** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3704" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #3705** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3705" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #3707** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3707" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #3710** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3710" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3710?utm_source=stack-comment).

2023-11-07 15:39 UTC, malmstein requested changes
As discussed offline:

- Rename SavedSitesSettingsRepository  to FavoritesFormFactorSettingsRepository
- Rename FavoritesAccessor to FavoritesDelegate 
- Move ViewMode un FavoritesAccessorto SavedSitesSettingsRepository
- Move ffs setting logic from FavoritesAccessor to SavedSitesSettingsRepository
-   - getInsertFavoriteFolder
-   - and all other functions that return a folder (String, List<String>)

2023-11-08 16:29 UTC, cmonfortep commented on saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/FavoritesAccessor.kt
> +interface FavoritesAccessor {
Skipping this one, as this is an internal class, and just a delegate. Docs are reflected in SavedSitesRepo api

2023-11-08 20:47 UTC, malmstein approved these changes
Looks good! I’m not sure about the `SyncSavedSitesRepository`, but it’s nothing that blocks this.

2023-11-08 20:47 UTC, malmstein commented on saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncEntitiesExtension.kt
this is not a SyncEntity, but an Entity. I’d rename this file to `EntitiesExtensions`

2023-11-08 20:47 UTC, malmstein commented on saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
Why do we need this? what’s the difference with the current Repository?

2023-11-08 20:57 UTC, cmonfortep commented on saved-sites/saved-sites-impl/src/main/java/com/duckduckgo/savedsites/impl/sync/SyncSavedSitesRepository.kt
As discussed, this repository will replace the current repository in sync related classes (aka. provider and persisters). Current repository will only be used by saved-sites feature (non-sync)

2023-11-08 20:57 UTC, merged