updating reference tests for protectionsState
duckduckgo/Android pull request #3821
Opened 2023-11-07 13:31 UTC by shakyShane

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2023-11-07 13:31 UTC, shakyShane commented
Current dependencies on/for this PR:
* develop
  * **PR #3821** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3821" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3821?utm_source=stack-comment).

2023-11-10 12:00 UTC, marcosholgado requested changes
Small change to simplify a bit.

2023-11-10 12:00 UTC, marcosholgado commented on app/src/test/java/com/duckduckgo/app/referencetests/brokensites/BrokenSitesReferenceTest.kt
> +        if (!testCase.protectionsEnabled) {
Can simplify to:

```
val url = Uri.parse(testCase.siteURL).host
whenever(mockUserAllowListRepository.isDomainInUserAllowList(url)).thenReturn(!testCase.protectionsEnabled)
```

2023-11-10 14:00 UTC, marcosholgado approved these changes
LGTM!

2023-11-10 14:03 UTC, merged