Add ability to block DRM via config
duckduckgo/Android pull request #3860
Opened 2023-11-14 00:11 UTC by nshuba

Task/Issue URL: https://app.asana.com/0/488551667048375/1205809518359270/f

### Description
Add ability to block DRM via config

### Steps to test this PR
- [ ] TBD

### UI changes
None

2023-11-14 08:47 UTC, marcosholgado commented on privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/DrmBlock.kt
> +interface DrmBlock {
I'd move all the new drm stuff and put in the site-permissions module. Privacy config is only for parsing so we are moving all the features away from it.

2023-11-14 23:15 UTC, nshuba commented on site-permissions/site-permissions-impl/src/main/java/com/duckduckgo/site/permissions/impl/SitePermissionsRepository.kt
> +@ContributesBinding(AppScope::class)
Not sure if there's a way to avoid the scope change here

2023-11-17 09:02 UTC, marcosholgado requested changes

2023-11-29 16:44 UTC, marcosholgado approved these changes
LGTM

2023-11-29 17:56 UTC, merged