Add reportFlow param to the broken site report pixel
duckduckgo/Android pull request #3881
Opened 2023-11-17 14:32 UTC by lmac012

Task/Issue URL: https://app.asana.com/0/488551667048375/1205957959864913/f

### Description

Add the reportFlow parameter to the broken site report pixel

### Steps to test this PR

#### Menu flow
- [ ] Navigate to the site breakage report screen through menu -> Report Broken Site
- [ ] Send report
- [ ] Verify that "reportFlow"="menu" param is included in the epbf pixel.

#### Dashboard flow
- [ ] Navigate to the site breakage report screen through Privacy Dashboard -> "Website not working?"
- [ ] Send report
- [ ] Verify that "reportFlow"="dashboard" param is included in the epbf pixel.

### No UI changes

2023-11-17 14:32 UTC, lmac012 commented
Current dependencies on/for this PR:
* develop
  * **PR #3881** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/3881?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/3881?utm_source=stack-comment).

2023-11-21 11:26 UTC, joshliebe commented on app/src/main/java/com/duckduckgo/app/brokensite/BrokenSiteActivity.kt
> +        val reportFlow = intent.getSerializableExtra<ReportFlow>(REPORT_FLOW)!!
We generally avoid `!!` in code (It's fine in tests), is there a way to handle the null case more gracefully?

2023-11-21 11:57 UTC, joshliebe requested changes
Other than the `!!`, LGTM and works as expected 👍
Once that's addressed, I'll approve 🙂

2023-11-21 15:02 UTC, joshliebe approved these changes
Re-tested, works as expected. Good job 👍

2023-11-21 21:05 UTC, merged