Remove sending 'mnot' pixel when notifications disabled
duckduckgo/Android pull request #4118
Opened 2024-01-25 14:05 UTC by nalcalag

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-01-25 14:05 UTC, nalcalag commented
* `develop`
  * **#4118** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4118?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nalcalag and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-01-29 14:52 UTC, marcosholgado commented on app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
> +                5L,
This need to be rolledback

2024-01-29 14:53 UTC, marcosholgado requested changes
Need to rollback the `scheduleUnusedAppNotifications()` changes

2024-01-29 14:53 UTC, marcosholgado commented on app/src/main/java/com/duckduckgo/app/notification/AndroidNotificationScheduler.kt
> +                8L,
Samesies

2024-02-06 10:58 UTC, marcosholgado approved these changes
LGTM

2024-02-06 10:59 UTC, merged