Sorted plugin points
duckduckgo/Android pull request #4155
Opened 2024-02-04 11:22 UTC by aitorvs

Task/Issue URL: https://app.asana.com/0/488551667048375/1206484244032077/f

### Description
See [asana task](https://app.asana.com/0/488551667048375/1206484244032077/f) and [API proposal](https://app.asana.com/0/488551667048375/1206484244031915)

### Steps to test this PR
Smoke test the app, this is backwards compatible change

2024-02-04 11:22 UTC, aitorvs commented
* `develop`
  * **#4155** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4155?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @aitorvs and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-02-05 14:14 UTC, CDRussell requested changes
I was testing this branch and the branch above. I noticed that when `@PriorityKey` is omitted, I'm not seeing the plugin show up as expected (I expect to see it after the others which do specify an explicit `PriorityKey`).

Sent screenshots offline to try diagnose, but assuming the issue is in this branch and not the one above.

2024-02-06 10:05 UTC, CDRussell approved these changes
LGTM, but please document at that priority key before merging https://github.com/duckduckgo/Android/pull/4155#discussion_r1478234301

2024-02-06 10:28 UTC, aitorvs commented on anvil/anvil-annotations/src/main/java/com/duckduckgo/anvil/annotations/PriorityKey.kt
> +annotation class PriorityKey(val priority: Int)
done

2024-02-06 10:37 UTC, merged