Refactor closing Privacy Dashboard on allowlist change
duckduckgo/Android pull request #4422
Opened 2024-04-11 14:20 UTC by lmac012

Task/Issue URL: https://app.asana.com/0/488551667048375/1206003719166625/f

### Description

The following line is fundamentally broken, because `site.userAllowList` also takes content blocking exceptions into account, so we're comparing apples to oranges: 

`site.userAllowList != site.domain in allowlistedDomains`

As a quick workaround, `.drop(1)` was added, and this PR fixes it properly by not depending on `site.userAllowList` at all, just observing the user allowlist state.

### Steps to test this PR

No behavior changes are expected as a result of this PR.

#### Privacy Dashboard is closed automatically after toggling protections
- [ ] Navigate to the Privacy Dashboard
- [ ] Toggle protections
- [ ] Verify that the screen closed itself after a slight delay (300ms) and the page reloaded automatically

#### Privacy Dashboard is closed automatically after toggling protections on Broken Site screen
- [ ] Navigate to the Privacy Dashboard
- [ ] Tap "Website not working?" to go to the Broken Site screen 
- [ ] Toggle protections
- [ ] Press back or submit report
- [ ] Verify that after exiting Broken Site screen you landed on the page which reloads automatically

#### Screen stays open for allowlisted domains
- [ ] Go to strava.com
- [ ] Navigate to the Privacy Dashboard
- [ ] Verify that protections are disabled and the screen doesn't close automatically

### No UI changes

2024-04-11 14:21 UTC, lmac012 commented
* **#4422** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4422?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lmac012 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-12 21:50 UTC, joshliebe commented
Looks good but the second step only works as expected if the toggle is on when tapping "Website not working?” but goes back to the privacy dashboard if the toggle is off when tapping "Website not working?” (It also doesn’t respect the toggle from the previous screen). I’ve attached a recording:

https://github.com/duckduckgo/Android/assets/3471025/2b1a3108-7462-46f8-a1a1-8451e694856b

2024-04-12 22:07 UTC, joshliebe requested changes
I tried the scenario I mentioned on develop and it works as expected.
Let me know when you’ve found the issue and I’ll check it again.

2024-04-13 11:48 UTC, lmac012 commented
Good catch @joshliebe, I missed one change. Should be fixed now.

2024-04-13 19:20 UTC, joshliebe approved these changes
Tested and working as expected now, nice one! ✅

2024-04-21 20:51 UTC, merged