Force Algorithmically dark mode
duckduckgo/Android pull request #4614
Opened 2024-06-05 10:56 UTC by malmstein

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-06-05 10:56 UTC, malmstein commented
* **#4614** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/4614?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @malmstein and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-10 14:05 UTC, CrisBarreiro commented on app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
> +                    canForceDarkMode = themingDataStore.theme != DuckDuckGoTheme.LIGHT,
I think we should also check is theme is SYSTEM_DEFAULT, and system default turns out to be light

2024-06-10 14:06 UTC, CrisBarreiro commented on app/src/main/java/com/duckduckgo/app/browser/BrowserTabFragment.kt
> +    @Suppress("NewApi") // This API and the behaviour described only apply to apps with targetSdkVersion ≥ TIRAMISU.
Do we need this? Our target is Upside Down Cake already

2024-06-10 14:08 UTC, CrisBarreiro commented on app/src/main/java/com/duckduckgo/app/appearance/AppearanceViewModel.kt
> +        settingsDataStore.experimentalWebsiteDarkMode = checked
We shouldn't be calling this from the main thread

2024-06-10 14:12 UTC, CrisBarreiro requested changes
Looks good overall, feel free to ignore minor issues, but I think we should address the edge case on system_default

2024-06-10 15:28 UTC, malmstein reviewed
Thanks @CrisBarreiro! I’ve added the edge case verification for system theming as suggested.

2024-06-13 11:09 UTC, CrisBarreiro approved these changes

2024-06-14 09:25 UTC, merged