Adds logic and UI when Autofill Remote feature flag disabled
duckduckgo/Android pull request #5047
Opened 2024-09-20 09:45 UTC by cmonfortep

Task/Issue URL: https://app.asana.com/0/0/1208236187388612/f 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-09-20 09:45 UTC, cmonfortep commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5047?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5047** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5047?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#5046** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5046?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5007** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5007?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cmonfortep and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-25 11:43 UTC, CDRussell requested changes

2024-09-25 11:43 UTC, CDRussell commented on autofill/autofill-impl/src/main/res/values/strings-autofill-impl.xml
> +    <string name="credentialManagementAutofillDisabledByConfigErrorMessage">Autofill for passwords is currently unavailable. We’re working to restore this in a future app update.</string>
should be in `donottranslate` until translations available?

2024-09-26 10:26 UTC, CDRussell approved these changes

2024-09-26 10:28 UTC, merged