Omnibar Refactor: Use LegacyOmnibar
duckduckgo/Android pull request #5073
Opened 2024-09-26 13:53 UTC by malmstein

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-09-26 13:53 UTC, malmstein commented
* **#5073** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5073?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @malmstein and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-07 10:22 UTC, 0nko requested changes
When testing the changes, I noticed that when you switch the omnibar position and come back to the browser window, the find-in-page mode is incorrectly triggered. Otherwise, it seems to be working as before.

https://github.com/user-attachments/assets/4dc7a7ae-1fc4-4039-ab11-6ac96bc36e78

2024-10-07 10:22 UTC, 0nko commented on app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
> +fun EditText.replaceTextChangedListener(textWatcher: TextChangedWatcher) {
Should this be in `EditTextExtensions`?

2024-10-07 11:56 UTC, malmstein commented on app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
> +fun EditText.replaceTextChangedListener(textWatcher: TextChangedWatcher) {
good idea, moving things around

2024-10-07 15:01 UTC, 0nko approved these changes
Nice work! :shipit:

2024-10-07 18:30 UTC, merged