Add feature flag for opening in new tab
duckduckgo/Android pull request #5124
Opened 2024-10-10 14:51 UTC by CrisBarreiro

Task/Issue URL: https://app.asana.com/0/0/1208511584623404/f 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-10-10 14:51 UTC, CrisBarreiro commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5124?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#5125** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5125?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5124** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#5121** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5121?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#5109** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5109?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#5110](https://github.com/duckduckgo/Android/pull/5110) <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5110?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CrisBarreiro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-16 21:38 UTC, joshliebe commented on privacy-config/privacy-config-api/src/main/java/com/duckduckgo/privacy/config/api/PrivacyFeatureName.kt
> +const val PRIVACY_REMOTE_CONFIG_URL = "https://www.jsonblob.com/api/1252645298605252608"
You probably don't want to change this 😁

2024-10-16 21:44 UTC, joshliebe commented on duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/DuckPlayerDataStore.kt
> +                prefs[Keys.DUCK_PLAYER_OPEN_IN_NEW_TAB] ?: true
nit: What’s the reason for defaulting to `true` here when the toggle defaults to `false`?

2024-10-16 21:47 UTC, joshliebe commented on duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
> +                Log.d("Cris", "observeShouldOpenInNewTab: $it")
```suggestion
                Log.d(“RealDuckPlayer", "observeShouldOpenInNewTab: $it")
```

2024-10-16 21:53 UTC, joshliebe commented on duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
> +                Log.d("Cris", "observeShouldOpenInNewTab: $it")
Remove this Log or use Timber instead.

2024-10-16 21:59 UTC, joshliebe requested changes
Works as expected but some debugging code slipped in. Remove that and I’ll approve 🙂

2024-10-17 09:23 UTC, joshliebe commented on duckplayer/duckplayer-impl/src/main/java/com/duckduckgo/duckplayer/impl/RealDuckPlayer.kt
> +            (if (!duckPlayerFeature.openInNewTab().isEnabled()) Unavailable else if (it) On else Off)
The enclosing parenthesis aren’t needed here anymore

2024-10-17 09:24 UTC, joshliebe approved these changes
Just the one [comment](https://github.com/duckduckgo/Android/pull/5124#discussion_r1804421660), LGTM!

2024-10-17 18:03 UTC, CrisBarreiro commented
### Merge activity

* **Oct 17, 2:03 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/duckduckgo/Android/5124).

2024-10-17 18:18 UTC, merged