Omnibar: React to Bottom Bar feature flag changes
duckduckgo/Android pull request #5220
Opened 2024-10-31 15:05 UTC by malmstein

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-10-31 15:05 UTC, malmstein commented
* **#5220** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5220?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @malmstein and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-31 16:49 UTC, 0nko requested changes
This solves the original problem but there is some code that needs to be removed.

I also noticed another problem: the toolbar icon is stuck on search when you disable the flag while on NTP.

2024-10-31 16:49 UTC, 0nko commented on app/src/main/java/com/duckduckgo/app/browser/omnibar/Omnibar.kt
> +                    binding.newOmnibarBottom
This shouldn’t be here. That’s what’s causing the padding issue in the NTP.

```suggestion
```

2024-11-04 09:41 UTC, 0nko approved these changes
Nice work! :shipit:

2024-11-04 09:51 UTC, merged