Update Settings design: Add feature flag & new Settings screen
duckduckgo/Android pull request #5300
Opened 2024-11-21 15:23 UTC by mikescamell

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2024-11-21 15:23 UTC, mikescamell commented
* **#5300** <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5300?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/duckduckgo/Android/5300?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `develop`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-23 13:48 UTC, malmstein requested changes
I don’t understand why have you copied the screen. What’s the benefit of doing it? We should start the new screen from scratch.

There’s a feature flag, have it disabled by default also for internal users. When you want to try the new screen, manually flip the switch and test it.

2024-11-23 13:50 UTC, malmstein commented on app/src/main/java/com/duckduckgo/app/settings/NewSettingsViewModel.kt
> +class NewSettingsViewModel @Inject constructor(
same here, this is inheriting all the bad practices we’ve been adding over the years. It’s going to take you much longer than if you start the screen from scratch with the new design.

2024-11-23 13:50 UTC, malmstein commented on subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
> +    private fun SharedPreferences.save(
is this needed?

2024-11-25 09:18 UTC, mikescamell commented on subscriptions/subscriptions-impl/src/main/java/com/duckduckgo/subscriptions/impl/RealSubscriptions.kt
> +    private fun SharedPreferences.save(
Just a formatting issue.

2024-11-26 20:03 UTC, malmstein requested changes
The toggle should be disabled by default

2024-11-26 20:03 UTC, malmstein commented on settings/settings-api/src/main/java/com/duckduckgo/settings/api/NewSettingsFeature.kt
> +    @Toggle.DefaultValue(true)
this is enabled by default to EVERYONE. it should be false

2024-11-27 09:39 UTC, malmstein approved these changes
works as expected, thanks @mikescamell !

2024-11-27 09:47 UTC, merged